######################## default configuration ####################
baseURL = "https://www.comparisongen.com/"
title = "ComparisonGen | Find top comparisons"
theme = "geeky-hugo"
languageName = "En"
languageCode = "en-us"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "20"
# google analytics
googleAnalytics = "G-J63KDESC64" # example: UA-123-45, for more info, read the article https://support.google.com/analytics/answer/1008080?hl=en
# disqus short name
disqusShortname = "dosely" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = [] # example: ["fr"] for disable french language

[taxonomies]
  tag = ""
  category = "categories"

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5

############################# Open Graph ##############################

[params]
  description = 'ComparisonGen uses generative AI to create daily comparisons from thousands of user reviews.'
  images = ['comparisongen-social-logo.png']
  title = 'ComparisonGen | Find top comparisons'

############################# Modules ##############################
[module]
[module.hugoVersion]
extended = true
min = "0.87.0"

############################# Outputs ##############################
[outputs]
home = ["HTML", "RSS", "JSON", "WebAppManifest"]

############################# Imaging ##############################
[imaging]
# See https://github.com/disintegration/imaging
# Default JPEG or WebP quality setting. Default is 75.
quality = 75

############################# Caches ###############################
[caches]
[caches.images]
dir = ":resourceDir/_gen"
maxAge = "720h"

[caches.assets]
dir = ":resourceDir/_gen"
maxAge = "720h"


############################# Markup ###############################
[markup]
[markup.goldmark.renderer]
unsafe = true


############################ Media types ############################
[mediaTypes]
[mediaTypes."application/manifest+json"]
suffixes = ["webmanifest"]

[mediaTypes."text/netlify"]
delimiter = ""
suffixes = [""]


############################ Output Format ###########################
[outputFormats]
[outputFormats.WebAppManifest]
mediaType = "application/manifest+json"
rel = "manifest"

######################### site variables ##############################
# customize your color and font from here.
[params.variables]
color_primary = "#009a84"
body_color = "#FFF"
text_color = "#555"
text_dark = "#222"
text_light = "#999"
border_color = "#e3efea"
black = "#000"
white = "#FFF"
light = "#f2f2f2"

# font variables
# base font size for full website, 
font_size = "15px" # default is 16px

# Font Scale Sizes
# "minorSecond": 1.067,
# "majorSecond": 1.125,
# "minorThird": 1.2,
# "majorThird": 1.25,
# "perfectFourth": 1.333,
# "augmentedFourth": 1.414,
# "perfectFifth": 1.5,
# "goldenRatio": 1.618
font_scale = "1.25" # default is "majorThird": 1.25

# Give your font name from google font. add font weight using ":wght@" and separate by ";"
# example: "Work Sans:wght@400;500;600"
font_primary = "Raleway:wght@400"
font_primary_type = "sans-serif"                  # [serif/sans-serif]
font_secondary = "Merriweather Sans:wght@400;700"
font_secondary_type = "sans-serif"                # [serif/sans-serif]
font_icon = "Font Awesome 6 Free"