############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "Contact"
url = "contact/"
weight = 2

[[main]]
name = "Reviews"
url = "#"
weight = 3
hasChildren = true

  [[main]]
  parent = "Reviews"
  name = "Tags"
  url = "tags/"
  weight = 1

  [[main]]
  parent = "Reviews"
  name = "Categories"
  url = "categories/"
  weight = 2

# footer menu
[[footer]]
name = "Home"
url = "/"
weight = 1

[[footer]]
name = "Contact"
url = "contact/"
weight = 3

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 4
