############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "Contact"
url = "contact/"
weight = 2

[[main]]
name = "Categories"
url = "categories/"
weight = 3

# footer menu
[[footer]]
name = "Home"
url = "/"
weight = 1

[[footer]]
name = "Contact"
url = "contact/"
weight = 3

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 4

[[footer]]
name = "Compara.cat"
url = "https://compara.cat"
weight = 5
